package engine;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Vector;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;

/**
 * Classe représentant l'interface graphique du programme, elle permet de charger un
 * index en mémoire, d'entrer une requete et d'afficher les résultas de recherche.
 * @author  Alexandre Burgert - Ossama Cadoret
 */
public class Bloup extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	
	private BufferedReader lecteur = null;
    
    /** Creates new form Bloup */
    public Bloup() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
    	this.setSize(800, 640);
    	jTabbedPane1 = new javax.swing.JTabbedPane();
        panelUtilisateur = new javax.swing.JPanel();
        jTextFieldResults = new javax.swing.JTextField();
        jScrollPaneResults = new javax.swing.JScrollPane();
        jTableResults = new javax.swing.JTable();
        jButtonBloup = new javax.swing.JButton();
        jScrollPaneSelection = new javax.swing.JScrollPane();
        jTextAreaSelection = new javax.swing.JTextArea();
        jPanelSearch = new javax.swing.JPanel();
        jTextFieldRequest = new javax.swing.JTextField();
        panelAdmin = new javax.swing.JPanel();
        jTextFieldPathIndex = new javax.swing.JTextField();
        jButtonSelectIndex = new javax.swing.JButton();
        jButtonLoadIndex = new javax.swing.JButton();
        jLabelLangue = new javax.swing.JLabel();
        jRadioButtonFrancais = new javax.swing.JRadioButton();
        jRadioButtonAnglais = new javax.swing.JRadioButton();
        
        highlighter = new DefaultHighlighter();
        indexLoaded = false;
        
        jRadioButtonFrancais.setSelected(true);
        jButtonLoadIndex.setEnabled(false);
        jTextFieldPathIndex.setEditable(false);
        fileChooser = new JFileChooser("./");
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.addChoosableFileFilter(new FileFilterIndex());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bloup");
        jTextFieldRequest.setText("Search");
        jTextFieldRequest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRequestKeyPressed(evt);
            }
        });
        
        jTextFieldResults.setEditable(false);
        jTextFieldResults.setBorder(null);
        jTextFieldResults.setCaretColor(new java.awt.Color(233, 233, 233));
        jTextFieldResults.setDisabledTextColor(new java.awt.Color(233, 233, 233));
        
        jTableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Documents"
            }
        ));
        jTableResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableResultsMouseClicked(evt);
            }
        });
        jScrollPaneResults.setViewportView(jTableResults);

        //jButtonBloup.setText("Bloup It");
        jButtonBloup.setIcon(new ImageIcon("./bloup_it.gif", "Bloup it"));
        jButtonBloup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBloupMouseClicked(evt);
            }
        });

        jTextAreaSelection.setColumns(20);
        jTextAreaSelection.setRows(5);
        jScrollPaneSelection.setViewportView(jTextAreaSelection);

        jTextFieldRequest.setText("Search");

        jTextFieldRequest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRequestKeyPressed(evt);
            }
        });

        GroupLayout jPanelSearchLayout = new GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanelSearchLayout.createSequentialGroup()
                .addComponent(jTextFieldRequest, GroupLayout.PREFERRED_SIZE, 305, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextFieldRequest, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        GroupLayout panelUtilisateurLayout = new GroupLayout(panelUtilisateur);
        panelUtilisateur.setLayout(panelUtilisateurLayout);
        panelUtilisateurLayout.setHorizontalGroup(
            panelUtilisateurLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelUtilisateurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUtilisateurLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelUtilisateurLayout.createSequentialGroup()
                        .addGroup(panelUtilisateurLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldResults, GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(jScrollPaneResults, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneSelection, GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE))
                    .addGroup(panelUtilisateurLayout.createSequentialGroup()
                        .addComponent(jPanelSearch, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonBloup)))
                .addContainerGap())
        );
        panelUtilisateurLayout.setVerticalGroup(
            panelUtilisateurLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelUtilisateurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUtilisateurLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBloup, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSearch, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUtilisateurLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneSelection, GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.LEADING, panelUtilisateurLayout.createSequentialGroup()
                        .addComponent(jTextFieldResults, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneResults, GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jTabbedPane1.addTab("Utisateur", panelUtilisateur);

        jButtonSelectIndex.setText("S\u00e9lectionner index");
        jButtonSelectIndex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSelectIndexMouseClicked(evt);
            }
        });

        jButtonLoadIndex.setText("Changer index");
        jButtonLoadIndex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoadIndexMouseClicked(evt);
            }
        });

        jLabelLangue.setText("Langue courante :");

        jRadioButtonFrancais.setSelected(true);
        jRadioButtonFrancais.setText("Fran\u00e7ais");
        jRadioButtonFrancais.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonFrancais.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonFrancais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFrancaisMouseClicked(evt);
            }
        });

        jRadioButtonAnglais.setText("Anglais");
        jRadioButtonAnglais.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonAnglais.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonAnglais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonAnglaisMouseClicked(evt);
            }
        });

        GroupLayout panelAdminLayout = new GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelAdminLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonAnglais)
                    .addComponent(jRadioButtonFrancais)
                    .addComponent(jLabelLangue)
                    .addGroup(panelAdminLayout.createSequentialGroup()
                        .addComponent(jTextFieldPathIndex, GroupLayout.PREFERRED_SIZE, 451, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelectIndex)
                        .addGap(42, 42, 42)
                        .addComponent(jButtonLoadIndex)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelAdminLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSelectIndex)
                    .addComponent(jButtonLoadIndex)
                    .addComponent(jTextFieldPathIndex, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabelLangue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonFrancais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonAnglais)
                .addContainerGap(425, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("Administration", panelAdmin);

        jTabbedPane1.getAccessibleContext().setAccessibleName("tabPanel");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        
        jRadioButtonAnglais.setVisible(false);
        jRadioButtonFrancais.setVisible(false);
        jLabelLangue.setVisible(false);
        
        pack();
    }// </editor-fold>

    private void jTableResultsMouseClicked(java.awt.event.MouseEvent evt) {                                           
        int row = jTableResults.getSelectedRow();
        String ligne, text = "";
        
        if (row >= 0) {
        	try {
				lecteur = new BufferedReader(new FileReader(jTableResults.getValueAt(row, 0).toString()+".clean"));
				
				while ((ligne = lecteur.readLine()) != null) {
					text += ligne + "\n";
				}
			} catch (FileNotFoundException e) {
				e.printStackTrace();
			} catch (IOException e) {
				e.printStackTrace();
			}
        	jTextAreaSelection.setText(text);
        	jTextAreaSelection.setCaretPosition(0);
        	jTextAreaSelection.setEditable(false);
        	jTextAreaSelection.setHighlighter(highlighter);
        	
        	String mots[] = reqCourante.split(" ");
        	for (String mot : mots) {
        		//System.out.println(mot);
        		int indice = 0, indice_prec = 0;
        		while ((indice = text.toLowerCase().indexOf(mot, indice+1)) != -1) {
        			//System.out.println(indice + " : " + mot.length());
        			if (indice == indice_prec) break;
        			try {
        				jTextAreaSelection.getHighlighter().addHighlight(indice, indice + mot.length(), new DefaultHighlighter.DefaultHighlightPainter(Color.CYAN));
        			} catch (BadLocationException e) {
        				e.printStackTrace();
        			}
        			indice_prec = indice;
        		}
        	}
        	
        }
    }   
    
    private void jTextFieldRequestKeyPressed(java.awt.event.KeyEvent evt) {                                             
        if (evt.getKeyChar() == evt.VK_ENTER) {
            jButtonBloupMouseClicked(null);
        }
    }                
    
    private void jButtonBloupMouseClicked(java.awt.event.MouseEvent evt) {
    	boolean english = true;
    	if (jRadioButtonFrancais.isSelected()) english = false;
    	
    	if (indexLoaded) {
	    	reqCourante = jTextFieldRequest.getText();
	    	
	    	Vector<VecteurTermes> res = interrogation.interroge(jTextFieldRequest.getText(), true);
	    	
	    	jTextFieldResults.setText("Results : " + res.size() + " documents found");
	    	
	    	DefaultTableModel model = new DefaultTableModel(new Object[] {"Document"}, res.size()) {
	    		public boolean isCellEditable(int iRowIndex, int iColumnIndex) {
	    			return false;
	    		}
	    	};
	    	int i = 0;
	    	for (VecteurTermes vec : res) {
	    		model.setValueAt(vec.getNom(), i, 0);
	    		i++;
	    	}
	    	
	    	jTableResults.setModel(model);
    	}
    	else {
    		jTextAreaSelection.setText("Vous devez charger l'index avant d'effectuer une recherche");
    	}
    }
    
    private void jButtonSelectIndexMouseClicked(java.awt.event.MouseEvent evt) {       
        int returnVal = fileChooser.showOpenDialog(Bloup.this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            jTextFieldPathIndex.setText(file.toString());
            jButtonLoadIndex.setEnabled(true);
        }
    }
    
    private void jButtonLoadIndexMouseClicked(java.awt.event.MouseEvent evt) {
    	System.out.println("Chargement de l'index");
        loadIndex();
    }
    
    private void jRadioButtonAnglaisMouseClicked(java.awt.event.MouseEvent evt) {                                                 
        jRadioButtonFrancais.setSelected(false);
        jRadioButtonAnglais.setSelected(true);
    }                                                

    private void jRadioButtonFrancaisMouseClicked(java.awt.event.MouseEvent evt) { 
        jRadioButtonAnglais.setSelected(false);
        jRadioButtonFrancais.setSelected(true);
    }              
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	ImageIcon icon = new ImageIcon("./bloup_it.gif");
            	Bloup bloup = new Bloup();
            	bloup.setIconImage(icon.getImage());
            	
                bloup.setVisible(true);
                
                bloup.getTextPaneRequest().setText("Loading index");
                //bloup.loadIndex();
                bloup.getTextPaneRequest().setText("Search");
                
            }
        });
    }
    
    public JTextField getTextPaneRequest() {
    	return this.jTextFieldRequest;
    }
    
    public void loadIndex() {
    	indexLoaded = true;
    	interrogation = new Interrogation(jTextFieldPathIndex.getText());
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonBloup;
    private javax.swing.JButton jButtonLoadIndex;
    private javax.swing.JButton jButtonSelectIndex;
    private javax.swing.JLabel jLabelLangue;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JRadioButton jRadioButtonAnglais;
    private javax.swing.JRadioButton jRadioButtonFrancais;
    private javax.swing.JScrollPane jScrollPaneResults;
    private javax.swing.JScrollPane jScrollPaneSelection;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableResults;
    private javax.swing.JTextArea jTextAreaSelection;
    private javax.swing.JTextField jTextFieldPathIndex;
    private javax.swing.JTextField jTextFieldRequest;
    private javax.swing.JTextField jTextFieldResults;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JPanel panelUtilisateur;
    
    private Interrogation	interrogation;
    private JFileChooser	fileChooser;
    private DefaultHighlighter highlighter;
    private String reqCourante;
    private boolean indexLoaded;
    // End of variables declaration                   
    
}
